<div id="slate_container"> 
	<div id="slate"> 
		<div id="slider">
			<img src="images/billboard/01.jpg" alt="" title="Paddles Up! Link Auction" />
			<img src="images/billboard/02.jpg" alt="" title="The LINK Amazing Race" />
			<img src="images/billboard/03.jpg" alt="" title="LINK Student Staff at the LINK Auction" />
			<img src="images/billboard/04.jpg" alt="" title="" />
			<img src="images/billboard/05.jpg" alt="" title="LINK Auction Prize Table" />
		</div>
	</div> 
</div>