<h3>Special Thanks</h3>	
<p>
	LINK would like to thank the following companies for their generous
	donations to the LINK program:
</p>
<ul>
	<li><a href="http://www.flipperspizzeria.com/our-locations/ucf/" class="external">Flipper's Pizzeria</a></li>
	<li><a href="http://seaworldparks.com/en/seaworld-orlando/" class="external">SeaWorld</a></li>
	<li><a href="http://rwc.sdes.ucf.edu/programs/outdoor-adventure" class="external">UCF Outdoor Adventure</a></li>
	<li><a href="http://www.ucfknights.com/" class="external">UCF Athletics</a></li>
	<li><a href="http://whps.sdes.ucf.edu/" class="external">Wellness and Health Promotions</a></li>
</ul>